package com.vbay.shared.enums;

public enum Event {
    //AUCTION
    AUCTION_CREATED,
    AUCTION_APPROVED,
    AUCTION_PUBLISHED,
    AUCTION_CLOSED,
    AUCTION_CANCLLED,
    // BIDDING PROCESS
    BID_PLACING,
    BID_RAISING,
    BID_TAKING,
    BID_CANCELLED,
    // USER 
    JOINING_AUCTION,
    WATCHING_AUCTION,
    QUITTING_AUCTION,
    ENABLING_AUTOBIDDING
}
