package com.vbay.shared.enums;

public enum RequestType {
    // Account
    REGISTER,
    LOGIN,
    LOGOUT,
    FORGOT_PASSWORD,
    VERIFY,
    UPDATE_PROFILE,

    // Auction lifecycle
    CLOSE_AUCTION,
    DECLARE_WINNER,
    NOTIFY_WINNER,

    // Watcher
    GET_AUCTION_LIST,
    GET_AUCTION_DETAIL,
    SEARCH_AUCTION,
    FILTER_AUCTION,
    SUBSCRIBE_ROOM,
    UNSUBSCRIBE_ROOM,
    GET_BID_HISTORY,

    // Bidder
    GET_MY_BID_LIST,
    JOIN_AUCTION,
    PLACE_BID,
    BUY_NOW,
    AUTO_BID,
    INCREASE_AUTOBID_MAX,
    CANCEL_BID,
    WATCH_AUCTION,
    QUIT_AUCTION,

    // Payment
    CREATE_PAYMENT,
    DEPOSIT_BALANCE,
    PAY_DEPOSIT,
    PAY_REST,
    VERIFY_PAYMENT,
    RETURN_DEPOSIT,

    // Seller
    UPLOAD_IMAGE,
    CREATE_AUCTION,
    CANCEL_AUCTION,
    // Admin
    ADMIN_GET_ALL_USERS,
    ADMIN_BAN_USER,
    ADMIN_KICK_USER,
    ADMIN_LOCK_USER,
    ADMIN_WARN_USER,
    ADMIN_DELETE_AUCTION,
    ADMIN_STOP_AUCTION,
    ADMIN_CONTINUE_AUCTION,
    ADMIN_GET_ALL_AUCTIONS,
    ADMIN_GET_PENDING_DEPOSITS,
    ADMIN_APPROVE_DEPOSIT,
    ADMIN_REJECT_DEPOSIT
}
